apiVersion: v1
kind: Pod
metadata:
  name: multi-conntainer-pod
  labels:
    env: Test
  annotations:
    purpose: "checking multi conntainer pod"
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
