apiVersion: v1
kind: Service
metadata:
  name: statefulset-headless-svc
  labels:
    project: roboshop
    purpose: statefulset-demo
spec:
  ports:
  - prot: 80
    name: web
  clusterIp: None
  selector:
    project: roboshop
    purpose: statefulset-demo
---

apiVersion: v1
kind: Service
metadata:
  name: statefulset-nrml-svc
  labels:
    project: roboshop
    purpose: statefulset-demo
spec:
  ports:
  - port: 80
    name: web
  selector:
    project: roboshop
    purpose: statefulset-demo
---

apiVersion: apps/v1
kind: StatefulSet 
metadata: 
  name: statefulset
  labels:
    project: roboshop
    purpose: statefulset-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      purpose: statefulset-demo
  service: statefulset-headless-svc
  template:
    metadata:
      labels:
        project: roboshop
        purpose: statefulset-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: efs-dynamic
      resources:
        requests:
          storage: 2Gi